### ISSUE TITLE
Is this is still active ? 

### ISSUE THREAD

**Issue by JayBabs** [b13bs/Hydro-Quebec-power-outages#1]
I'm curious about this module, let me know if you need help ! 
Je suis curieux de faire une V2, j'ai essayé le module mais ca semble désuet. Fais moi signe si tu as besoin d'aide

**Comment by b13bs** [comment]
Hey, I would be surprised if it still works. I did no significant improvements since 2016. 
Good luck to you if you want to build a new one!

**Comment by JayBabs** [comment]
Pourquoi on se lance pas le défi ?
Mon adresse courriel est le ***@***.***

**Comment by b13bs** [comment]
I wrote to you in private
